export const FORMULARIO_PEDIDO = 'FORMULARIO_PEDIDO'
export const OBTENER_PEDIDOS = 'OBTENER_PEDIDOS';
export const OBTENER_PEDIDOS_USER = 'OBTENER_PEDIDOS_USER';
export const AGREGAR_PEDIDO = 'AGREGAR_PEDIDO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PEDIDO_ACTUAL = 'PEDIDO_ACTUAL';
export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO';
export const PEDIDO_ERROR = 'PEDIDO_ERROR';
export const ACTUALIZAR_PEDIDO = 'ACTUALIZAR_PEDIDO';
export const ELEGIR_PEDIDO = 'ELEGIR_PEDIDO';

export const TAREAS_PEDIDO = 'TAREAS_PEDIDO';
export const FORMULARIO_TAREA = 'FORMULARIO_TAREA';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const LIMPIAR_TAREA = 'LIMPIAR_TAREA';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_PAGOS = 'OBTENER_PAGOS';
export const FORMULARIO_PAGO = 'FORMULARIO_PAGO';
export const AGREGAR_PAGO = 'AGREGAR_PAGO';
export const VALIDAR_FORMULARIO_PAGO = 'VALIDAR_FORMULARIO_PAGO';
export const ELIMINAR_PAGO = 'ELIMINAR_PAGO';
export const ACTUALIZAR_PAGO = 'ACTUALIZAR_PAGO';
export const ELEGIR_PAGO = 'ELEGIR_PAGO';
export const PAGO_ERROR = 'PAGO_ERROR';
export const PAGO_ACTUAL = 'PAGO_ACTUAL';

export const AGREGAR_NOTA = 'AGREGAR_NOTA';
export const OBTENER_NOTAS = 'OBTENER_NOTAS';
export const FORMULARIO_NOTA = 'FORMULARIO_NOTA';
export const VALIDAR_FORMULARIO_NOTA = 'VALIDAR_FORMULARIO_NOTA';
export const ACTUALIZAR_NOTA = 'ACTUALIZAR_NOTA';
export const ELIMINAR_NOTA = 'ELIMINAR_NOTA';
export const ELEGIR_NOTA = 'ELEGIR_NOTA';
export const NOTA_ERROR = 'NOTA_ERROR';
export const NOTA_ACTUAL = 'NOTA_ACTUAL';